#See https://aka.ms/customizecontainer to learn how to customize your debug container and how Visual Studio uses this Dockerfile to build your images for faster debugging.

FROM mcr.microsoft.com/dotnet/aspnet:7.0 AS base
WORKDIR /app
EXPOSE 80
EXPOSE 443
EXPOSE 6000

FROM mcr.microsoft.com/dotnet/sdk:7.0 AS build
WORKDIR /src
COPY ["OpenAiRestApi.csproj", "."]
RUN dotnet restore "./OpenAiRestApi.csproj"
COPY . .
WORKDIR "/src/."
RUN dotnet build "OpenAiRestApi.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "OpenAiRestApi.csproj" -c Release -o /app/publish /p:UseAppHost=false

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
RUN rm /app/appsettings.Development.json
ENTRYPOINT ["dotnet", "OpenAiRestApi.dll"]