{
 "title": "OpenAI Tokens",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "prometheus" },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values(up{job=\"kube-state-metrics\"},cluster)"
    }
   },
   {
    "name": "openai_name",
    "label": "OpenAI",
    "query": {
     "query": "label_values(openai_completion_tokens_total{cluster=\"$cluster\"},openai_name)"
    }
   },
   {
    "name": "tenant_name",
    "label": "Tenant",
    "query": {
     "query": "label_values(openai_completion_tokens_total{cluster=\"$cluster\"},tenant_name)"
    }
   },
   {
    "name": "method_name",
    "label": "Method",
    "query": {
     "query": "label_values(openai_completion_tokens_total{cluster=\"$cluster\"},method_name)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Average Prompt Tokens Total by Tenant",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by (openai_name, tenant_name, method_name) (openai_prompt_tokens_total{cluster=~\"$cluster\",openai_name=~\"$openai_name\", tenant_name=~\"$tenant_name\", method_name=~\"$method_name\"})",
     "legendFormat": "{{openai_name}}-{{tenant_name}}-{{method_name}}"
    }
   ]
  },
  {
   "title": "Average Completion Tokens Total by Tenant",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 4, "x": 4, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by (openai_name, tenant_name, method_name) (openai_completion_tokens_total{cluster=~\"$cluster\", openai_name=~\"$openai_name\", tenant_name=~\"$tenant_name\", method_name=~\"$method_name\"})",
     "legendFormat": "{{openai_name}}-{{tenant_name}}-{{method_name}}"
    }
   ]
  },
  {
   "title": "Average Total Tokens Total by Tenant",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 4, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by (openai_name, tenant_name, method_name) (openai_total_tokens_total{cluster=~\"$cluster\", openai_name=~\"$openai_name\", tenant_name=~\"$tenant_name\", method_name=~\"$method_name\"})",
     "legendFormat": "{{openai_name}}-{{tenant_name}}-{{method_name}}"
    }
   ]
  },
  {
   "title": "Prompt Tokens Percentiles",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 4, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "histogram_quantile(0.80, sum(rate(openai_prompt_tokens_bucket{cluster=~\"$cluster\", openai_name=~\"$openai_name\", tenant_name=~\"$tenant_name\", method_name=~\"$method_name\"}[$__rate_interval])) by (le))",
     "legendFormat": "P80"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(openai_prompt_tokens_bucket{cluster=~\"$cluster\", openai_name=~\"$openai_name\", tenant_name=~\"$tenant_name\", method_name=~\"$method_name\"}[$__rate_interval])) by (le))",
     "legendFormat": "P90"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(openai_prompt_tokens_bucket{cluster=~\"$cluster\", openai_name=~\"$openai_name\", tenant_name=~\"$tenant_name\", method_name=~\"$method_name\"}[$__rate_interval])) by (le))",
     "legendFormat": "P99"
    }
   ]
  },
  {
   "title": "Completion Tokens Percentiles",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 4, "x": 16, "y": 0 },
   "targets": [
    {
     "expr": "histogram_quantile(0.80, sum(rate(openai_completion_tokens_bucket{cluster=~\"$cluster\", openai_name=~\"$openai_name\", tenant_name=~\"$tenant_name\", method_name=~\"$method_name\"}[$__rate_interval])) by (le))",
     "legendFormat": "P80"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(openai_completion_tokens_bucket{cluster=~\"$cluster\", openai_name=~\"$openai_name\", tenant_name=~\"$tenant_name\", method_name=~\"$method_name\"}[$__rate_interval])) by (le))",
     "legendFormat": "P90"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(openai_completion_tokens_bucket{cluster=~\"$cluster\", openai_name=~\"$openai_name\", tenant_name=~\"$tenant_name\", method_name=~\"$method_name\"}[$__rate_interval])) by (le))",
     "legendFormat": "P99"
    }
   ]
  },
  {
   "title": "Total Tokens Percentiles",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 4, "x": 20, "y": 0 },
   "targets": [
    {
     "expr": "histogram_quantile(0.80, sum(rate(openai_total_tokens_bucket{cluster=~\"$cluster\", openai_name=~\"$openai_name\", tenant_name=~\"$tenant_name\", method_name=~\"$method_name\"}[$__rate_interval])) by (le))",
     "legendFormat": "P80"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(openai_total_tokens_bucket{cluster=~\"$cluster\", openai_name=~\"$openai_name\", tenant_name=~\"$tenant_name\", method_name=~\"$method_name\"}[$__rate_interval])) by (le))",
     "legendFormat": "P90"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(openai_total_tokens_bucket{cluster=~\"$cluster\", openai_name=~\"$openai_name\", tenant_name=~\"$tenant_name\", method_name=~\"$method_name\"}[$__rate_interval])) by (le))",
     "legendFormat": "P99"
    }
   ]
  },
  {
   "title": "Rate of Change of Prompt Tokens",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 4, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "sum by(openai_name) (rate(openai_prompt_tokens_total{openai_name=~\"$openai_name\"}[$__rate_interval]))",
     "legendFormat": "{{openai_name}}"
    }
   ]
  },
  {
   "title": "Rate of Change of Completion Tokens",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 4, "x": 4, "y": 9 },
   "targets": [
    {
     "expr": "sum by(openai_name) (rate(openai_completion_tokens_total{openai_name=~\"$openai_name\"}[$__rate_interval]))",
     "legendFormat": "{{openai_name}}"
    }
   ]
  },
  {
   "title": "Rate of Change of Total Tokens",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 4, "x": 8, "y": 9 },
   "targets": [
    {
     "expr": "sum by(openai_name) (rate(openai_total_tokens_total{openai_name=~\"$openai_name\"}[$__rate_interval]))",
     "legendFormat": "{{openai_name}}"
    }
   ]
  },
  {
   "title": "Request Token Heatmap",
   "type": "heatmap",
   "gridPos": { "h": 9, "w": 4, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "sum(increase(openai_prompt_tokens_bucket{cluster=~\"$cluster\", openai_name=~\"$openai_name\", tenant_name=~\"$tenant_name\", method_name=~\"$method_name\"}[$__rate_interval])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Completion Token Heatmap",
   "type": "heatmap",
   "gridPos": { "h": 9, "w": 4, "x": 16, "y": 9 },
   "targets": [
    {
     "expr": "sum(increase(openai_completion_tokens_bucket{cluster=~\"$cluster\", openai_name=~\"$openai_name\", tenant_name=~\"$tenant_name\", method_name=~\"$method_name\"}[$__rate_interval])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Total Token Heatmap",
   "type": "heatmap",
   "gridPos": { "h": 9, "w": 4, "x": 20, "y": 9 },
   "targets": [
    {
     "expr": "sum(increase(openai_total_tokens_bucket{cluster=~\"$cluster\", openai_name=~\"$openai_name\", tenant_name=~\"$tenant_name\", method_name=~\"$method_name\"}[$__rate_interval])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Average Prompt Tokens Processed by Tenant",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "avg by (cluster, openai_name, tenant_name, method_name) (openai_prompt_tokens_processed{cluster=~\"$cluster\", openai_name=~\"$openai_name\", tenant_name=~\"$tenant_name\", method_name=~\"$method_name\"})",
     "legendFormat": "{{openai_name}}-{{tenant_name}}-{{method_name}}"
    }
   ]
  },
  {
   "title": "Average Completion Tokens Processed by Tenant",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 18 },
   "targets": [
    {
     "expr": "avg by (cluster, openai_name, tenant_name, method_name) (openai_completion_tokens_processed{cluster=~\"$cluster\", openai_name=~\"$openai_name\", tenant_name=~\"$tenant_name\", method_name=~\"$method_name\"})",
     "legendFormat": "{{openai_name}}-{{tenant_name}}-{{method_name}}"
    }
   ]
  },
  {
   "title": "Average Total Tokens Processed by Tenant",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 18 },
   "targets": [
    {
     "expr": "avg by (cluster, openai_name, tenant_name, method_name) (openai_total_tokens_processed{cluster=~\"$cluster\", openai_name=~\"$openai_name\", tenant_name=~\"$tenant_name\", method_name=~\"$method_name\"})",
     "legendFormat": "{{openai_name}}-{{tenant_name}}-{{method_name}}"
    }
   ]
  }
 ]
}