apiVersion: v1
kind: ConfigMap
metadata:
  name: openai-configmap
data:
  aspNetCoreEnvironment: Production
  appsettings.json: |-
    {
      "Logging": {
        "LogLevel": {
          "Default": "Information",
          "Microsoft.AspNetCore": "Warning"
        }
      },
      "AllowedHosts": "*",
      "ChatCompletionsOptions": {
        "Temperature": 0.8,
        "MaxTokens": 16000
      },
      "Prometheus": {
        "Enabled": true,
        "Histograms": {
          "PromptTokens": {
            "Start": 10,
            "Width": 10,
            "Count": 10
          },
          "CompletionTokens": {
            "Start": 100,
            "Width": 100,
            "Count": 10
          },
          "TotalTokens": {
            "Start": 100,
            "Width": 100,
            "Count": 10
          }
        }
      },
      "AzureOpenAI": {
        "SystemPrompt": "The assistant is helpful, creative, clever, and very friendly.",
        "Services": {
          "AlphaOpenAI": {
            "Endpoint": "https://AlphaOpenAI.openai.azure.com/",
            "Type": "azuread",
            "Version": "2023-08-01-preview",
            "Deployment": "gpt-35-turbo-16k",
            "Model": "gpt-35-turbo-16k",
            "MaxResponseTokens": 1000,
            "MaxRetries": 3
          },
          "BetaOpenAI": {
            "Endpoint": "https://BetaOpenAI.openai.azure.com/",
            "Type": "azuread",
            "Version": "2023-08-01-preview",
            "Deployment": "gpt-35-turbo-16k",
            "Model": "gpt-35-turbo-16k",
            "MaxResponseTokens": 1000,
            "MaxRetries": 3
          }
        }
      },
      "TenantAzureOpenAIMappings": {
        "contoso": "AlphaOpenAI",
        "fabrikam": "BetaOpenAI"
      },
      "Kestrel": {
        "Endpoints": {
          "http": {
            "Protocols": "Http1",
            "Url": "http://*:80"
          },
          "Grpc": {
            "Protocols": "Http2",
            "Url": "http://*:6000"
          }
        }
      }
    }